[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "python start.py"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app"
